//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendaDeAutomoveis.Repository.ConnectionContext.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GDC_Vendas
    {
        public string Id { get; set; }
        public decimal Valor { get; set; }
        public string Tipo_Entrega { get; set; }
        public string Status { get; set; }
        public bool Termo_Autorizacao { get; set; }
        public string IdPerformance { get; set; }
        public string IdCliente { get; set; }
        public string IdFormaPagamento { get; set; }
        public string IdVeiculo { get; set; }
    
        public virtual GDC_Clientes GDC_Clientes { get; set; }
        public virtual GDC_Formas_Pagamentos GDC_Formas_Pagamentos { get; set; }
        public virtual GDC_Perfomances GDC_Perfomances { get; set; }
        public virtual GDC_Veiculos GDC_Veiculos { get; set; }
    }
}
