//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendaDeAutomoveis.Repository.ConnectionContext.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GDCarsEntities : DbContext
    {
        public GDCarsEntities()
            : base("name=GDCarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GDC_Bancos> GDC_Bancos { get; set; }
        public virtual DbSet<GDC_Clientes> GDC_Clientes { get; set; }
        public virtual DbSet<GDC_Cores_Externa> GDC_Cores_Externa { get; set; }
        public virtual DbSet<GDC_Enderecos> GDC_Enderecos { get; set; }
        public virtual DbSet<GDC_Formas_Pagamentos> GDC_Formas_Pagamentos { get; set; }
        public virtual DbSet<GDC_Logins> GDC_Logins { get; set; }
        public virtual DbSet<GDC_Perfomances> GDC_Perfomances { get; set; }
        public virtual DbSet<GDC_Rodas> GDC_Rodas { get; set; }
        public virtual DbSet<GDC_Uploads> GDC_Uploads { get; set; }
        public virtual DbSet<GDC_Veiculos> GDC_Veiculos { get; set; }
        public virtual DbSet<GDC_Vendas> GDC_Vendas { get; set; }
    }
}
